name: "Test"
on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
        flake8: [
            'flake8==4.*',
            'flake8==5.*',
            'flake8==6.*',
            'flake8==7.*',
            'git+https://github.com/pycqa/flake8.git@main',
        ]
        exclude:
        - python: '3.7'
          flake8: 'git+https://github.com/pycqa/flake8.git@main'
        - python: '3.7'
          flake8: 'flake8==7.*'
        - python: '3.7'
          flake8: 'flake8==6.*'
        - python: '3.8'
          flake8: 'git+https://github.com/pycqa/flake8.git@main'
        - python: '3.12'
          flake8: 'flake8==4.*'
        - python: '3.13'
          flake8: 'flake8==4.*'

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install flake8-force
        run: |
          pip install "${{ matrix.flake8 }}"
          pip install -v .

      - name: Setup test environment
        run: |
          python -V
          pip install pytest
          pip freeze

      - name: Run tests
        run: |
          pushd tests
          python -m pytest .
          popd

      - name: Run flake8
        run: |
          flake8
