name: "Test"
on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        flake8-version: [
            'flake8==4.*',
            'flake8==5.*',
            'git+https://github.com/pycqa/flake8.git@main',
        ]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flake8-force
        run: |
          pip install "${{ matrix.flake8-version }}"
          pip install -v .

      - name: Setup test environment
        run: |
          python -V
          pip install pytest
          pip freeze

      - name: Run tests
        run: |
          pushd tests
          python -m pytest .
          popd

      - name: Run flake8
        run: |
          flake8
